app = "taskmaster-relay"
primary_region = "iad"

[env]
LOG_LEVEL = "debug"
PORT = "8080"
SERVICE_NAME = "taskmaster"
TASKMASTER_PATH = "/sss"
UPSTREAM_URL = "https://taskmaster-mcp.fly.dev"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8_080
min_machines_running = 1
processes = [ "app" ]

[vm]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
